export const ADD_TO_CART="ADD_TO_CART";
export const GET_ALL_CART_ITEMS="GET_ALL_CART_ITEMS";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const GET_TEST_ARR="GET_TEST_ARR";
export const UPDATE_TEST_ARR="UPDATE_TEST_ARR";